#!/usr/bin/env ruby
# Validate the files given on the command line with a java-based validator.

require 'socket'
proxy_host = 'localhost'
# proxy_host = 'satyagraha.sacred.net'
proxy_port = '3128'

jarfile = 'xmlvalidator.jar'
jarpath = File.join(File.dirname(__FILE__), jarfile)

if not File.exists? jarpath
  STDERR.puts "Can't find #{jarfile} (checked #{File.dirname(__FILE__)})"
  exit
end

ARGV.each do |file|
  if (not File.exists? file) 
    STDERR.puts "File #{file} does not exist, skipping.\n";
    next;
  end

  cmd = "java -Dhttp.proxyHost=#{proxy_host} -Dhttp.proxyPort=#{proxy_port} -Dfile='#{file}' -jar '#{jarpath}'"
  puts cmd
  puts `#{cmd}`
end
